# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e1bf79e1ccf44ef5b9b8ebc59e9b2dff174624a09fc349e236bf0315e9a20e4f6f511eb299526c9095013660165fbe3bfcbcf9bd5cbce59d54e23d44ea5114e

test:
  secret_key_base: 885e655151c1270c944f1b030a009ca908ecee5db76d307357a1d9e4baf8d747c4be03acd098471256c3962953ce28da976c37dd3363c5f7ef792e634203fa34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
